// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// prior_nonc_t
double prior_nonc_t(double x1, double c1, double sigma, double nu, double lam1);
RcppExport SEXP _BHSBVAR_prior_nonc_t(SEXP x1SEXP, SEXP c1SEXP, SEXP sigmaSEXP, SEXP nuSEXP, SEXP lam1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type lam1(lam1SEXP);
    rcpp_result_gen = Rcpp::wrap(prior_nonc_t(x1, c1, sigma, nu, lam1));
    return rcpp_result_gen;
END_RCPP
}
// prior_t_n
double prior_t_n(double x1, double c1, double sigma, double nu);
RcppExport SEXP _BHSBVAR_prior_t_n(SEXP x1SEXP, SEXP c1SEXP, SEXP sigmaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t_n(x1, c1, sigma, nu));
    return rcpp_result_gen;
END_RCPP
}
// prior_t_p
double prior_t_p(double x1, double c1, double sigma, double nu);
RcppExport SEXP _BHSBVAR_prior_t_p(SEXP x1SEXP, SEXP c1SEXP, SEXP sigmaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t_p(x1, c1, sigma, nu));
    return rcpp_result_gen;
END_RCPP
}
// prior_t
double prior_t(double x1, double c1, double sigma, double nu);
RcppExport SEXP _BHSBVAR_prior_t(SEXP x1SEXP, SEXP c1SEXP, SEXP sigmaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t(x1, c1, sigma, nu));
    return rcpp_result_gen;
END_RCPP
}
// post_A_max
double post_A_max(Rcpp::NumericVector par, arma::cube pA, arma::cube pdetA, arma::cube pH, arma::mat pP, arma::mat pP_sig, arma::cube pR_sig, arma::mat kappa1, arma::mat y1, arma::mat x1, arma::mat omega, arma::mat somega, int nlags);
RcppExport SEXP _BHSBVAR_post_A_max(SEXP parSEXP, SEXP pASEXP, SEXP pdetASEXP, SEXP pHSEXP, SEXP pPSEXP, SEXP pP_sigSEXP, SEXP pR_sigSEXP, SEXP kappa1SEXP, SEXP y1SEXP, SEXP x1SEXP, SEXP omegaSEXP, SEXP somegaSEXP, SEXP nlagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type pA(pASEXP);
    Rcpp::traits::input_parameter< arma::cube >::type pdetA(pdetASEXP);
    Rcpp::traits::input_parameter< arma::cube >::type pH(pHSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pP(pPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pP_sig(pP_sigSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type pR_sig(pR_sigSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type kappa1(kappa1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type somega(somegaSEXP);
    Rcpp::traits::input_parameter< int >::type nlags(nlagsSEXP);
    rcpp_result_gen = Rcpp::wrap(post_A_max(par, pA, pdetA, pH, pP, pP_sig, pR_sig, kappa1, y1, x1, omega, somega, nlags));
    return rcpp_result_gen;
END_RCPP
}
// MAIN
Rcpp::List MAIN(arma::mat y1, arma::mat x1, arma::mat omega, arma::mat somega, int nlags, arma::cube pA, arma::cube pdetA, arma::cube pH, arma::mat pP, arma::mat pP_sig, arma::cube pR_sig, arma::mat kappa1, arma::mat A_max, int itr, int burn, int thin, arma::mat scale1, int h1_irf, bool acc_irf, double ci, Rcpp::StringVector VarNames, Rcpp::Function line_plot, Rcpp::Function acf_plot);
RcppExport SEXP _BHSBVAR_MAIN(SEXP y1SEXP, SEXP x1SEXP, SEXP omegaSEXP, SEXP somegaSEXP, SEXP nlagsSEXP, SEXP pASEXP, SEXP pdetASEXP, SEXP pHSEXP, SEXP pPSEXP, SEXP pP_sigSEXP, SEXP pR_sigSEXP, SEXP kappa1SEXP, SEXP A_maxSEXP, SEXP itrSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP scale1SEXP, SEXP h1_irfSEXP, SEXP acc_irfSEXP, SEXP ciSEXP, SEXP VarNamesSEXP, SEXP line_plotSEXP, SEXP acf_plotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type somega(somegaSEXP);
    Rcpp::traits::input_parameter< int >::type nlags(nlagsSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type pA(pASEXP);
    Rcpp::traits::input_parameter< arma::cube >::type pdetA(pdetASEXP);
    Rcpp::traits::input_parameter< arma::cube >::type pH(pHSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pP(pPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pP_sig(pP_sigSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type pR_sig(pR_sigSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type kappa1(kappa1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A_max(A_maxSEXP);
    Rcpp::traits::input_parameter< int >::type itr(itrSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< int >::type h1_irf(h1_irfSEXP);
    Rcpp::traits::input_parameter< bool >::type acc_irf(acc_irfSEXP);
    Rcpp::traits::input_parameter< double >::type ci(ciSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type VarNames(VarNamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type line_plot(line_plotSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type acf_plot(acf_plotSEXP);
    rcpp_result_gen = Rcpp::wrap(MAIN(y1, x1, omega, somega, nlags, pA, pdetA, pH, pP, pP_sig, pR_sig, kappa1, A_max, itr, burn, thin, scale1, h1_irf, acc_irf, ci, VarNames, line_plot, acf_plot));
    return rcpp_result_gen;
END_RCPP
}
